name: MiyooFW

on: [push, pull_request]

# TODO: Use composites?
# TODO: Don't checkout all modules all the time?
jobs:
  build-logo:
    runs-on: ubuntu-latest
    container:
      image: arcnor/toolchain-bittboy:steward

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: build
      run: cd logo && make -f Makefile.bittboy
    - uses: actions/upload-artifact@v2
      with:
        name: artifacts-bittboy-bittboy_logo
        path: boot-logo

  build-uboot-spi:
    runs-on: ubuntu-latest
    container:
      image: arcnor/toolchain-bittboy:steward

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: install deps
      run: apt update && apt install -y swig
    - name: build
      run: cd uboot && make licheepi_nano_spiflash_defconfig && make
    - uses: actions/upload-artifact@v2
      with:
        name: uboot-spi-flash
        path: uboot/u-boot-sunxi-with-spl.bin

  build-uboot-sd:
    runs-on: ubuntu-latest
    container:
      image: arcnor/toolchain-bittboy:steward

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: install deps
      run: apt update && apt install -y swig
    - name: build
      run: cd uboot && make licheepi_nano_defconfig && make
    - uses: actions/upload-artifact@v2
      with:
        name: uboot-sd
        path: uboot/u-boot-sunxi-with-spl.bin

  build-kernel-4bit:
    runs-on: ubuntu-latest
    container:
      image: arcnor/toolchain-bittboy:steward

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: build
      run: cd kernel && make miyoo_defconfig && make zImage
    - uses: actions/upload-artifact@v2
      with:
        name: kernel-4bit
        path: kernel/arch/arm/boot/zImage

  build-daemon:
    runs-on: ubuntu-latest
    container:
      image: arcnor/toolchain-bittboy:steward

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: build
      run: cd daemon && make
    - uses: actions/upload-artifact@v2
      with:
        name: daemon
        path: daemon/daemon

  build-gmenunx:
    runs-on: ubuntu-latest
    container:
      image: arcnor/toolchain-bittboy:steward

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: build
      run: cd gmenunx && make -f Makefile.miyoo
    - uses: actions/upload-artifact@v2
      with:
        name: gmenunx
        path: gmenunx/objs/miyoo

